language: ruby
rvm:
  - 2.4
services:
  - mysql
dist: trusty
env:
  - DB=mysql
  - DEV_TEST_DB_USER=root
  - DEV_TEST_DB_PASSWORD=mkcd61al
  - SECRET_KEY_BASE_DEV=23cf7e8dde2c43fabd5e48153f4fcb676132ac44081e51d1553269958d3f1ea7e96e69928c09d221cbc753bfc81c14367d48616f9925aed39a3d5a7b6426afe4
  - SECRET_KEY_BASE_TEST=fe124b4f3714c3c728de589d0979b8f4a0bab136fff2b3b4d524b04a27383fc5a0c77f2c9c897298e94bef9429b24252828be63dd9edb5d3f29d968d11bc89cc
sudo: required
before_install:
  # - chmod +x ./script/*
  - bash --verbose ./script/travis_mysql_5.7.sh
  - bash --verbose ./script/mysql-reset-root-password.sh
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database rightGift_test'
