language: ruby

rvm:
  - 2.4

services:
  - mysql

dist: trusty

env:
  global:
    - RAILS_ENV=test
    - CODECLIMATE_REPO_TOKEN=a32506db14b041d2b8c917fa932859a4aa5c4973
  matrix:
    - DB=mysql
    - DEV_TEST_DB_USER=root
    - DEV_TEST_DB_PASSWORD=mkcd61al

sudo: required

before_install:
  - bash --verbose ./script/travis_mysql_5.7.sh
  - bash --verbose ./script/mysql-reset-root-password.sh

before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database rightGift_test'

script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - bundle exec rspec && bundle exec codeclimate-test-reporter

# addons:
#   mysql: "5.7"
#   code_climate:
#     - repo_token: a32506db14b041d2b8c917fa932859a4aa5c4973

# after_success:
#   - bundle exec codeclimate-test-reporter
