language: ruby
rvm:
  - 2.4
services:
  - mysql
dist: trusty
env:
  - DB=mysql
sudo: required
before_install:
  -  chmod +x ./script/* 
  - ./script/travis_mysql_5.7.sh
  - ./script/mysql-reset-root-password.sh
script:
  - bundle exec rake dev:setup
  - bundle exec rspec spec/
