language: ruby
rvm:
  - 2.4
services:
  - mysql
dist: trusty
env:
  - DB=mysql
sudo: required
before_install:
  # - chmod +x ./script/*
  # - ./script/travis_mysql_5.7.sh
  # - ./script/mysql-reset-root-password.sh
  - sudo service mysql stop || echo "mysql not stopped"
  - sudo stop mysql-5.6 || echo "mysql-5.6 not stopped"
  - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
  - wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
  - sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server
  - sudo mysql_upgrade
  - set -x
  - set -e
  - sudo service mysql stop || echo "mysql not stopped"
  - sudo stop mysql-5.6 || echo "mysql-5.6 not stopped"
  - sudo  mysqld_safe --skip-grant-tables &
  - sleep 4
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo kill -9 `sudo cat /var/lib/mysql/mysqld_safe.pid`
  - sudo kill -9 `sudo cat /var/run/mysqld/mysqld.pid`
  - sudo service mysql restart
  - sleep 4
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database rightGift_test'
