language: ruby
rvm:
  - 2.4
services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.7
    - mysql-server-core-5.7
    - mysql-client-core-5.7
    - mysql-client-5.7
script:
  - bundle exec rake dev:setup
  - bundle exec rspec spec/
