language: ruby

rvm:
  - 2.4

services:
  - mysql

dist: trusty

env:
  global:
    - RAILS_ENV=test
    - CC_TEST_REPORTER_ID=338f52719dd2e9a66aeac86ae64395e4e5f198d64873b70b778fecd5f8d95255
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
  matrix:
    - DB=mysql
    - DEV_TEST_DB_USER=root
    - DEV_TEST_DB_PASSWORD=mkcd61al

sudo: required

before_install:
  # - chmod +x ./script/*
  - bash --verbose ./script/travis_mysql_5.7.sh
  - bash --verbose ./script/mysql-reset-root-password.sh

before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database rightGift_test'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - bundle exec rspec
  # - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

addons:
  code_climate:
    - repo_token: 338f52719dd2e9a66aeac86ae64395e4e5f198d64873b70b778fecd5f8d95255

after_success:
  - bundle exec codeclimate-test-reporter
